(()=>{
 const A=SiteAppState,C=MultiShiftCoverage,S=SiteScheduleLogic,V=WeeklyAssignmentView;let state=A.load(),dateKey=A.todayKey(),selected=[],draft=null;const $=id=>document.getElementById(id),esc=A.esc;
 function assignable(){return S.shiftCatalog(state).filter(def=>def.id!=='unassigned'&&C.engineersForShift(state,def.id).length&&def.defaultStart&&def.defaultEnd);}
 function suggested(){const active=new Set(S.visibleShiftIds(state,dateKey));if(active.has('weekend-day')&&active.has('weekend-mid'))return ['weekend-day','weekend-mid'];if(active.has('weekday-morning')&&active.has('weekday-mid'))return ['weekday-morning','weekday-mid'];const list=assignable().filter(d=>active.has(d.id));return list.slice(0,2).map(d=>d.id);}
 function ensureSelection(){const ids=new Set(assignable().map(d=>d.id));selected=selected.filter(id=>ids.has(id));if(!selected.length)selected=suggested();}
 function currentPublished(){return selected.length?C.publishedWeeklyPlan(state,dateKey,selected):null;}
 function renderChoices(){ensureSelection();$('shiftChoices').innerHTML=assignable().map(def=>{const eng=C.engineersForShift(state,def.id),tsa=C.tsasForShift(state,def.id),active=S.shiftActiveOnDate(state,def.id,dateKey),checked=selected.includes(def.id);return `<label class="shift-choice ${checked?'selected':''}"><input type="checkbox" data-shift="${esc(def.id)}" ${checked?'checked':''}><div><strong>${esc(def.name)}</strong><span>${eng.length} engineers • ${tsa.length} TSA${tsa.length===1?'':'s'} • ${esc(S.formatTime(def.defaultStart))}–${esc(S.formatTime(def.defaultEnd))}</span><small>${active?'Active on selected date':'Selected date is outside normal workdays; builder will use the next operational block'}</small></div></label>`;}).join('');document.querySelectorAll('[data-shift]').forEach(x=>x.addEventListener('change',()=>{selected=x.checked?[...selected,x.dataset.shift]:selected.filter(id=>id!==x.dataset.shift);draft=null;render();}));}
 function renderPeriod(){if(!selected.length){$('periodHint').textContent='Choose one or more shifts.';return;}const p=C.operationalPeriod(state,dateKey,selected),names=selected.map(id=>S.shiftDefinition(state,id)?.name||id).join(' + ');$('periodHint').innerHTML=`<strong>${esc(A.fmtRange(p.startDate,p.endDate))}</strong> • ${esc(names)} • weekly base assignment`;
 }
 function renderHealth(plan){if(!plan){$('healthRow').innerHTML='';return;}const h=C.health(state,plan),stale=C.weeklyPlanStale(state,plan);$('healthRow').innerHTML=[`<div class="health-card ${h.issues.length?'bad':'good'}"><strong>Site coverage</strong><small>${esc(h.issues.join(' • ')||'All 38 sites covered in every generated window.')}</small></div>`,`<div class="health-card ${h.warnings.some(x=>x.includes('TSA'))?'warn':'good'}"><strong>TSA coverage</strong><small>${esc(h.warnings.filter(x=>x.includes('TSA')).join(' • ')||'TSA support assigned wherever active TSA staffing is available.')}</small></div>`,`<div class="health-card ${stale?'warn':'good'}"><strong>Weekly stability</strong><small>${stale?'Shift defaults, vacations, or workload rules changed after this plan was generated. Regenerate before publishing.':'Base weekly plan matches current shift defaults and staffing.'}</small></div>`].join('');}
 function render(){
  $('builderDate').value=dateKey;renderChoices();renderPeriod();const published=currentPublished(),plan=draft||published;$('publishBtn').disabled=!draft;$('clearBtn').disabled=!published;
  if(draft){$('builderStatus').className='badge warning';$('builderStatus').textContent='Preview ready';}else if(published){const stale=C.weeklyPlanStale(state,published);$('builderStatus').className=`badge ${stale?'warning':'success'}`;$('builderStatus').textContent=stale?'Published • refresh needed':'Published';}else{$('builderStatus').className='badge';$('builderStatus').textContent='Not published';}
  if(plan){$('previewLegend').innerHTML=V.legend();$('previewTable').innerHTML=V.table(state,plan);$('previewHandoffs').innerHTML=V.handoffStrip(state,plan);renderHealth(plan);}else{$('previewLegend').innerHTML='';$('previewTable').innerHTML='<div class="empty-panel"><strong>Generate a plan to preview assignments.</strong><span>The published plan will persist for the full operational week.</span></div>';$('previewHandoffs').innerHTML='';renderHealth(null);}
 }
 $('builderDate').addEventListener('change',e=>{dateKey=e.target.value||dateKey;selected=[];draft=null;render();});
 $('useSuggested').addEventListener('click',()=>{selected=suggested();draft=null;render();});
 $('generateBtn').addEventListener('click',()=>{if(!selected.length)return;draft=C.generateWeeklyPlan(state,dateKey,selected);render();});
 $('publishBtn').addEventListener('click',()=>{if(!draft)return;state=A.save(C.publishWeeklyPlan(state,draft));draft=null;render();});
 $('clearBtn').addEventListener('click',()=>{const p=currentPublished();if(!p)return;state=A.save(C.clearWeeklyPlan(state,p));draft=null;render();});
 render();
})();
